longhorn/go-spdk-helper

pkg/spdk/types/raid.go

The two functions complain
``` 
json: cannot unmarshal object into Go struct field BdevRaidInfo.driver_specific.raid.base_bdevs_list of type string
```
and
```
json: cannot unmarshal object into Go struct field BdevRaidInfo.base_bdevs_list of type string
```
after a raid bdev is created.

Fix unmarshal failures in BdevGetBdevs and BdevRaidGetBdevs

---

pkg/nvme/initiator.go
pkg/types/types.go

1. Make TransportAddress of Initiator configurable
~~2. "nvme connect" doesn't support "-o" option~~ => old nvme-clie doesn't support `-o`, will check in the environment check script.

Make TransportAddress of Initiator configurable

---

pkg/types/types.go

Fix error:
```
app/cmd/nvmecli/nvmecli.go:32:18: undefined: types.LocalIP
app/cmd/nvmecli/nvmecli.go:70:18: undefined: types.LocalIP
app/cmd/nvmecli/nvmecli.go:129:18: undefined: types.LocalIP
```

types: Add missed const LocalIP

---

pkg/types/types.go

ctrlr_loss_timeout_sec: time to wait until ctrlr is reconnected before deleting ctrlr
reconnect_delay_sec: time to delay a reconnect trial
fast_io_fail_timeout_sec: time to wait until ctrlr is reconnected before failing I/O to ctrlr
A time sequence example is:
- Suppose at 0 seconds, a NVMe-oF controller's connection fails and there are some unfinished I/O requests.
- Between 0 and 15 seconds, these I/O requests are reported as failures and the NVMe-oF controller tries to reconnect.
- At 5 seconds, the NVMe-oF controller successfully reconnects and resumes normal operation.
- If at 5 seconds, the NVMe-oF controller does not successfully reconnect, then it tries to reconnect every 5 seconds until it succeeds or exceeds 30 seconds.
- If at 30 seconds, the NVMe-oF controller still does not …

ReconnectDelaySec can't be more than FastIoFailTimeoutSec

---

pkg/jsonrpc/types.go

Error message is not reliable. For example, error code is -19, but the error message can be
```
rpc error: code = Unknown desc = error sending message, id 70658, method bdev_raid_delete, params {Name:pvc-39ce670f-145c-4592-9f2f-df0d29ccc130-e-548f4718}: {
"code": -19,
"message": "raid bdev pvc-39ce670f-145c-4592-9f2f-df0d29ccc130-e-548f4718 not found"
}
```
and not always "No such device"

Only check jsonRPCError code

---

pkg/nvme/initiator.go
pkg/nvme/nvme.go
pkg/nvme/nvmecli.go

When a controller is in a resetting and connecting state, the device list becomes incomplete and broken. The resulting error causes the engine validation logic to run into an error and leads to volume detachment. To resolve this, if "connecting state" is returned, retry the validation logic in SPDK engine.
Longhorn/longhorn#5744

Handle controller's resetting and connecting state

---

app/cmd/basic/bdev_lvol.go

https://github.com/longhorn/go-spdk-helper/pull/39

fix: missing context argument in client

---

app/cmd/basic/nvmf.go
pkg/util/device.go

Longhorn 7567
Issue longhorn/longhorn#7567
Fix using deprecated option of blockdev command in go-spdk-helper

Fix using deprecated option of blockdev command in go-spdk-helper

---

pkg/nvme/initiator.go

Issue Longhorn/longhorn#7615
--force is too aggressive and might make dmsetup command stuck.

Do not use --force for dmsetup remove command

---

app/cmd/nvmecli/nvmecli.go
pkg/nvme/initiator.go
pkg/spdk/spdk_test.go
pkg/util/dmsetup.go

Issue Longhorn/longhorn#7579
Try to replace the target of dm device if it is unable to be removed.
- If the target is unable to be replaced. The filesystem should be in `rw` state.
- Instead, it is in `ro` state.

Try to replace the target of dm device if it is unable to be removed

---

app/cmd/basic/bdev_nvme.go
app/cmd/nvmecli/nvmecli.go
pkg/nvme/initiator.go
pkg/nvme/nvmecli.go
pkg/spdk/client/basic.go
pkg/spdk/spdk_test.go
pkg/spdk/types/nvme.go
pkg/types/types.go

Issue Longhorn/longhorn#7697
- Allow deferred dm device deletion when deleting a replica
When deleting a replica, no need to delete a dm device by a blocking method.
- spdk_tgt: add KeepAliveTimeoutMs in BdevNvmeSetOptions
Add KeepAliveTimeoutMs using the default value 10000 milliseconds as upstream in BdevNvmeSetOptions.
This is just for making debugging process easier in the future.
- nvme: set ctrl-loss-tmo to 30 seconds for "nvme connect"
Default ctrl-loss-tmo is 600 seconds which is too long so that the pod deletion will be stuck for 600 seconds when the volume is problematic.
**Not sure if 30 seconds is a correct value for now. It is just for relieve the stuck case.**
Ref: https://documentation.suse.com/sles/15-SP4/html/SLES-all/cha-nvmeof.html

Allow dm deferred deletion and update the ctrl-loss-tmo of "nvme connect" to 30 seconds

---

app/cmd/basic/bdev_nvme.go
app/cmd/basic/log.go
main.go
pkg/spdk/client/basic.go
pkg/spdk/types/log.go

Add log level and flag operations

---

pkg/spdk/client/basic.go

Issue #7578
When BdevLvolGet is called with lvol name empty, which means to retrieve all bdevs from spdk, the BdevLvolGetXattr function fails. We have to call it with the bdev name retrieved from spdk.

(fix)lvol: get_xattr lvol name in BdevLvolGet

---

pkg/util/device.go

More explanation is at https://github.com/longhorn/longhorn/issues/8088#issuecomment-1982300242
longhorn/longhorn#8088

Automatically add Longhorn device to the group id 6 (disk group) by default

---

pkg/util/device.go

The device should be in the first raw of the device list from "lsblk -l ...". However, The command "lsblk -l ..." unexpectedly sorts the device list, leading to the failure of device detection.
Longhorn/longhorn#7672
Issue #

Fix DetectDevice()

---

app/cmd/spdksetup/spdksetup.go
pkg/spdk/setup/setup.go
pkg/types/types.go

GetDiskStatus: return *types.DiskStatus rather than a json string

---

app/cmd/basic/bdev_nvme.go
pkg/spdk/client/basic.go
pkg/spdk/types/nvme.go
pkg/types/types.go

Issue Longhorn/longhorn#8354
Set multipath of nvmf controller to disable, because Longhorn doesn't reply on the multipath feature of the nvmf controller.

Set multipath of nvmf controller to disable

---

Dockerfile.dapper

Dockerfile: update spdk to 62a8f8a

---

pkg/jsonrpc/client.go
pkg/spdk/spdk_test.go
pkg/spdk/types/bdev.go
pkg/util/device.go
scripts/validate

https://github.com/longhorn/longhorn/issues/7448

fix: golangci-lint error

---

app/cmd/advanced/expose.go
app/cmd/basic/nvmf.go
pkg/spdk/client/advanced.go
pkg/spdk/client/basic.go
pkg/spdk/spdk_test.go

Issue longhorn/longhorn#8551
To expose a logical volume and attach it to the local node, NGUID should be provided.

Add NGUID to NvmfSubsystemAddNs

---

Dockerfile.dapper
app/cmd/dmsetup/dmsetup.go
app/cmd/nvmecli/nvmecli.go
main.go
pkg/nvme/initiator.go
pkg/nvme/nvme.go
pkg/nvme/nvmecli.go
pkg/spdk/spdk_test.go
pkg/util/device.go
pkg/util/dmsetup.go

feat(upgrade): support engine suspension and target switchover

---

pkg/spdk/client/basic.go
pkg/spdk/spdk_test.go

This is needed when upgrading from a version without the user_created xattr to a new one with this flag. Otherwise, the snapshot will not be listed in the UI.
Issue longhorn/longhorn#9054

fix(lvol): set user_created to true if no xattr found

---

pkg/types/types.go

Issue Longhorn/longhorn#9190
Allows to re-establish the connection more quickly and prevent long stuck.

feat(nvmf): decrease reconnect-delay-sec to 2 seconds

---

app/cmd/dmsetup/dmsetup.go
app/cmd/nvmecli/nvmecli.go
app/cmd/spdksetup/spdksetup.go
app/cmd/spdktgt/spdktgt.go
pkg/nvme/initiator.go
pkg/nvme/nvme.go
pkg/nvme/nvmecli.go
pkg/spdk/setup/setup.go
pkg/spdk/spdk_test.go
pkg/util/device.go
pkg/util/dmsetup.go
pkg/util/executor.go

Issue `None`
Remove camel casing in alias to align convention with other repos.
`None`
`None`

style(import): align alias naming with convention used in other repos

---

pkg/spdk/client/basic.go
pkg/spdk/spdk_test.go

feat: add func BdevLvolGetWithFilter

---

app/cmd/basic/bdev_lvol.go
pkg/spdk/client/basic.go
pkg/spdk/spdk_test.go
pkg/spdk/types/lvol.go

Longhorn 9488
Issue longhorn/longhorn#9488

feat: add API bdev_lvol_rename

---

pkg/nvme/nvmecli.go

Issue Longhorn/longhorn#9818
The current default value for --reconnect-delay is 10 seconds. We can reduce this value to 2 seconds.
- Advantages: Faster IO resumption post-upgrade
- Disadvantages: Increased frequency of retries

feat: decrease the reconnect delay of v2 volume nvme initiator

---

.gitignore
pkg/types/types.go

fix: decrease ctrlr_loss_timeout_sec for base bdev

---

pkg/types/types.go

chore: add an example for the timeouts of spdk bdev_nvme_attach_controller

---

pkg/nvme/initiator.go
pkg/nvme/nvme.go
pkg/nvme/nvmecli.go
pkg/spdk/client/advanced.go
pkg/types/types.go
pkg/util/device.go

Issue Longhorn/longhorn#9919
- fix: always ensure endpoint creation
- fix: reload device numbers while reusing linear dm device
- refactor: improve log messages and api docs
Signed-off-by: Derek Su <derek.su@suse.com>

fix: always ensure endpoint creation

---

app/cmd/basic/bdev_lvol.go
app/cmd/nvmecli/nvmecli.go
pkg/spdk/client/basic.go
pkg/spdk/types/lvol.go

ref: https://github.com/longhorn/longhorn/issues/6341
- Fix `resize` command: https://spdk.io/doc/jsonrpc.html
```
Example request:
{
"jsonrpc": "2.0",
"method": "bdev_lvol_resize",
"id": 1,
"params": {
"name": "51638754-ca16-43a7-9f8f-294a0805ab0a",
"size_in_mib": 2
}
}
Example response:
{
"jsonrpc": "2.0",
"id": 1,
"result": true
}
```
- Fix `nvmecli` to use `c.GlobalString` instead of `c.String`

feat(backingimage): support v2 backing image

---

pkg/spdk/client/basic.go

Issue Longhorn/longhorn#9221
While creating a big lvstore, 60-second timeout is apparently not enough. To address the issue, we replace SendCommand which has only 60-second timeout with SendCommandWithLongTimeout.

feat: increase the timeout of lvstore creation

---

app/cmd/basic/bdev_lvol.go
pkg/spdk/client/basic.go

Issue 
Longhorn/longhorn#8666
Longhorn/longhorn#9488
We need a convenient way to get all info of a snapshot lvol including its checksum.  For now, we can put the checksum in lvol xattr map.

fix: improve lvol snapshot checksum get

---

pkg/spdk/client/basic.go

feat: add func BdevLvolGetByName

---

pkg/spdk/client/basic.go
pkg/spdk/types/bdev.go

https://github.com/longhorn/longhorn/issues/10472

feat: add func BdevGetIostat

---

pkg/types/types.go

ref: https://github.com/longhorn/longhorn/issues/10520
related:
- https://github.com/longhorn/longhorn/issues/10044
- https://github.com/longhorn/longhorn/issues/10522
sometimes initiator.stop() cannot be finished in 60 secs, we then unexpose the target which makes the nvme disconnect command stuck forever.
The hanging command can prevent the container from terminating and make the uninstallation fail.

fix: extend command timeout to 180 secs

---

.github/workflows/build.yml
scripts/test

Issue longhorn/longhorn#10497
- mount hugetlbfs if it doesn't exist
- use OCI runners

chore(workflow): mount hugetlbfs if it doesn't exist and use OCI runners

---

scripts/test

Issue Longhorn/longhorn#10684
During CI testing, spdk_tgt is repeatedly started and stopped. To prevent interference between concurrent CI tasks, only one SPDK CI test is allowed at a time by using a file lock.

test: only one SPDK CI test is allowed at a time by using a file lock

---

app/cmd/basic/ublk.go
app/cmd/nvmecli/nvmecli.go
main.go
pkg/initiator/initiator.go
pkg/initiator/nvme.go
pkg/initiator/nvmecli.go
pkg/initiator/ublk_id_generator.go
pkg/jsonrpc/types.go
pkg/spdk/client/ublk.go
pkg/spdk/spdk_test.go
pkg/spdk/types/ublk.go
pkg/types/types.go
pkg/util/device.go

Issue # https://github.com/longhorn/longhorn/issues/9456

feat: implement ublk frontend for v2 data engine

---

app/cmd/basic/ublk.go
pkg/initiator/initiator.go
pkg/initiator/ublk_id_generator.go
pkg/spdk/client/ublk.go
pkg/spdk/types/ublk.go

Change ublkd to use int32 so that it is consistent with other fields
longhorn/longhorn#9456

feat: implement ublk frontend for v2 data engine - part 2

---

pkg/jsonrpc/types.go

This error code will be returned when trying to stop a non-existing checksum hash.
Issue Longhorn/longhorn#10563

fix: add error code no such process

---

app/cmd/basic/bdev_lvol.go
pkg/spdk/client/basic.go
pkg/spdk/types/lvol.go

Issue https://github.com/longhorn/longhorn/issues/10037

feat(lvol): add APIs for delta snapshot rebuilding

---

app/cmd/basic/bdev_raid.go
pkg/spdk/client/basic.go
pkg/spdk/spdk_test.go
pkg/spdk/types/raid.go

https://github.com/longhorn/longhorn/issues/8022
- supporting create bdev raid with specific uuid if needed

feat(raid): support specific UUID for creating RAID bdev #8022
