longhorn/go-spdk-helper

app/cmd/basic/bdev_nvme.go
pkg/nvme/initiator.go
pkg/spdk/client/basic.go
pkg/spdk/spdk_test.go
pkg/spdk/types/bdev.go
pkg/spdk/types/nvme.go

Notice that the unit test is corrected but the link of `spdk` repo in `Dockerfile.dapper` is not updated yet. 
We will update it when [this PR](https://github.com/longhorn/spdk/pull/6) is merged.

Fix issues, Add functions and descriptions, Introduce APIs 

---

pkg/spdk/client/client.go
pkg/types/types.go

- Add Close function to SPDK client
- Add FrontendSPDKTCPBlockDev constant

Add Close function to SPDK client and Add `FrontendSPDKTCPBlockDev` constant

---

pkg/nvme/nvme.go

nvme discover does not respect the -s option, so we need to filter the output

Fix DiscoverTarget

---

pkg/nvme/nvme.go

Remove "libhugetlbfs: ERROR: Line too long when parsing mounts" from string
```
nvme list -v -o json
libhugetlbfs: ERROR: Line too long when parsing mounts
{
"Devices":[
{
"HostNQN":"nqn.2014-08.org.nvmexpress:uuid:ec28c0e7-2793-565d-9c2f-02d2c5b24dee",
"HostID":"aac8e3b4-fcdd-4645-a976-f754f969e4e6",
"Subsystems":[
{
"Subsystem":"nvme-subsys0",
"SubsystemNQN":"nqn.2023-01.io.longhorn.spdk:pvc-5a6abf13-b225-4cef-825c-27a690143274-e-b0352c83",
"Controllers":[
{
"Controller":"nvme0",
"SerialNumber":"00000000000000000000",
"ModelNumber":"SPDK bdev Controller",
"Firmware":"23.05",
"Transport":"tcp",
...
```
Longhorn 5744

Fix JSON parsing error

---

main.go
pkg/jsonrpc/client.go
pkg/nvme/nvme.go
pkg/util/device.go

The output of "nvme list" command varies in format across different distributions and versions when the verbose option is used.
Longhorn/longhorn#5744

Fix GetDevices

---

pkg/nvme/nvme.go
pkg/nvme/nvmecli.go

Already tested on SLES 15.4 (nvme-cli 2.0) and Ubuntu 20.04 (nvme-cli 1.16)
Longhorn/longhorn#5744

Support nvme-cli v1 and v2

---

pkg/jsonrpc/types.go

Longhorn/longhorn#6071
longhorn/longhorn#6155

Add broken pipe error check function

---

pkg/jsonrpc/client.go
pkg/jsonrpc/types.go

Use separate decoder for each cmd call

---

pkg/nvme/nvmecli.go

Fix maximum lba data type

---

Dockerfile.dapper
pkg/spdk/spdk_test.go
pkg/spdk/target/target.go

To make the test env the same as the release env.

Update dapper and unit test

---

app/cmd/basic/bdev_lvol.go
pkg/spdk/client/basic.go
pkg/spdk/types/bdev.go
pkg/spdk/types/lvol.go

Longhorn/longhorn#6604
based on https://github.com/longhorn/spdk/pull/18

xattr: add BdevLvolGetXattr method and cmd

---

pkg/nvme/initiator.go
pkg/nvme/nvme.go
pkg/nvme/nvmecli.go

Use nvme cli in container instead

---

app/cmd/basic/bdev_lvol.go
pkg/spdk/client/basic.go
pkg/spdk/types/bdev.go
pkg/spdk/types/lvol.go

fragmap: add BdevLvolGetFragmap

---

app/cmd/advanced/device.go
app/cmd/advanced/expose.go
app/cmd/basic/bdev.go
app/cmd/basic/bdev_aio.go
app/cmd/basic/bdev_lvol.go
app/cmd/basic/bdev_lvstore.go
app/cmd/basic/bdev_nvme.go
app/cmd/basic/bdev_raid.go
app/cmd/basic/nvmf.go
app/cmd/spdktgt/spdktgt.go
pkg/jsonrpc/client.go
pkg/jsonrpc/types.go
pkg/nvme/initiator.go
pkg/nvme/nvme.go
pkg/nvme/nvmecli.go
pkg/spdk/client/advanced.go
pkg/spdk/client/client.go
pkg/spdk/spdk_test.go
pkg/spdk/target/target.go
pkg/types/types.go

https://github.com/longhorn/longhorn/issues/6106

Launch async message send and make the client thread-safe 

---

pkg/jsonrpc/client.go
pkg/spdk/client/basic.go

https://github.com/longhorn/longhorn/issues/7253

Fix the wrong timer for the json client response handling

---

pkg/jsonrpc/client.go

jsonrpc: Improve the timer in the response read function

---

pkg/nvme/initiator.go
pkg/nvme/nvme.go
pkg/spdk/target/target.go
pkg/types/types.go
pkg/util/device.go
pkg/util/dmsetup.go
pkg/util/execute.go

https://github.com/longhorn/longhorn/issues/7357

Add a linear dm device on the top of a nvme device

---

pkg/jsonrpc/client.go
pkg/types/types.go

Fix stuck client caused by blocking channel operation and wrong timeout value

---

pkg/nvme/nvme.go
pkg/nvme/nvmecli.go
pkg/spdk/types/lvol.go

nvme: pass both --hostid and --hostnqn to discover and connect commands

---

pkg/nvme/initiator.go

linear dm device is not required for backup and restore.
Longhorn/longhorn#6138

initiator: make linear dm device optional

---

app/cmd/nvmecli/nvmecli.go

nvmecli: update initiator arguments of start and stop functions

---

.drone.yml
Dockerfile.dapper
pkg/nvme/initiator.go
pkg/spdk/spdk_test.go
scripts/build
scripts/ci
scripts/test

https://github.com/longhorn/longhorn/issues/7509

ci: add .drone.yml and fix errors

---

Dockerfile.dapper
app/cmd/basic/bdev_lvol.go
pkg/spdk/client/basic.go
pkg/spdk/spdk_test.go
pkg/spdk/types/lvol.go

lvol: add xattr option to snapshot creation

---

pkg/spdk/types/bdev.go

Add DriverSpecific check in GetBdevType

---

go.mod
go.sum
pkg/nvme/initiator.go
pkg/nvme/nvmecli.go
pkg/spdk/spdk_test.go
pkg/spdk/target/target.go
pkg/util/device.go
pkg/util/dmsetup.go
vendor/github.com/longhorn/go-common-libs/ns/crypto.go
vendor/github.com/longhorn/go-common-libs/ns/executor.go
vendor/github.com/longhorn/go-common-libs/ns/filelock.go
vendor/github.com/longhorn/go-common-libs/sys/sys.go
vendor/modules.txt

Update arguments of namespaced Execute()

---

Dockerfile.dapper

Dockerfile: update spdk to 880cd9c

---

Dockerfile.dapper

Dockerfile: update spdk to eabc229

---

Dockerfile.dapper

Dockerfile: update golang to 1.22.2

---

.github/workflows/build.yml
Dockerfile.dapper
scripts/test

https://github.com/longhorn/longhorn/issues/8039

ci: change to use GitHub actions

---

Dockerfile.dapper

Dockerfile: replace bci-base 15.5 with golang 1.22

---

.gitignore

chore(gitignore): ignore coverage.out

---

Dockerfile.dapper

chore(nvme): update nvme-cli to v2.9.1

---

Dockerfile.dapper

chore(dockerfile): update spdk to a6478cd

---

pkg/types/types.go

types: Add shallow copy state const

---

pkg/nvme/initiator.go

dmDeviceAndEndpointCleanupRequired is for cleaning up both the dm device and the endpoint.
Issue Longhorn/longhorn#9032
dmDeviceAndEndpointCleanupRequired is for cleaning up both the dm device and the endpoint.

fix(initiator): rename dmDeviceCleanupRequired to dmDeviceAndEndpointCleanupRequired

---

app/cmd/spdksetup/spdksetup.go
go.mod
go.sum
pkg/spdk/setup/setup.go
vendor/github.com/longhorn/go-common-libs/ns/executor.go
vendor/github.com/longhorn/go-common-libs/types/file.go
vendor/modules.txt

Issue Longhorn/longhorn#8813
If DRIVER_OVERRIDE is not specified, the driver will be automatically detected.

feat(disk driver): set env DRIVER_OVERRIDE if provided

---

Dockerfile.dapper

chore: update nvme-cli to v2.10.2

---

pkg/jsonrpc/client.go

fix: improve json client

---

app/cmd/basic/bdev_lvol.go
pkg/spdk/client/basic.go
pkg/spdk/types/lvol.go

Issue https://github.com/longhorn/longhorn/issues/10421

feat(lvol): add stop snapshot checksum API

---

Dockerfile.dapper

Issue `None`
Fix build failures:
```
Problem accessing the file at the specified URI:
File '/repositories/devel:languages:python:backports/SLE_15/devel:languages:python:backports.repo' not found on medium 'https://download.opensuse.org/'
```
`None`
`None`

fix(build): repo URL not found on medium

---

app/cmd/basic/bdev_lvol.go
pkg/spdk/client/basic.go
pkg/spdk/types/lvol.go

Issue https://github.com/longhorn/longhorn/issues/9808

feat(lvol): add BdevLvolSetXattr method and cmd

---

Dockerfile.dapper
Makefile

chore(Makefile): update SRC_BRANCH to master

---

Dockerfile.dapper
Makefile
pkg/spdk/spdk_test.go

chore(dockerfile): add cache buster to avoid using old dependencies
